// netlify/functions/hreflang.js
// Generates hreflang markup for all international markets and queues as approval items.
//
// POST /api/hreflang { queue: true }  — generate + queue items
// GET  /api/hreflang?brand=pickl      — return markup only (no queue)
//
// Markets:
//   Pickl (6):   Bahrain, KSA, Qatar, Egypt, Jordan (/pickl-jordan/), Oman
//   Bonbird (3): Oman, Pakistan, Qatar

const { createApproval, ok, bad, preflight, parseBody } = require('./_lib/store');
const { getBrand, getBrandSlugs } = require('./_lib/brands-config');
const { getMarketsForBrandAsync } = require('./_lib/international-config');

const CORS = { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' };

// Hreflang config is DERIVED from the brand + SEO-market config (CLAUDE.md #12) —
// it used to be a hardcoded per-brand slug list, which silently went stale when
// Bonbird's site was rebuilt to ISO market URLs (/ae/ /om/ /qa/ /pk/) on 2026-08-18
// and would have emitted wrong hreflang right after the site's own was fixed.
// Locale = <language>-<ISO countryCode from the market record>.
// Home market: brandsConfig.homeMarketSlug (Bonbird '/ae/'; Pickl = site root).
async function buildHreflangConfig(brand) {
  const b       = await getBrand(brand);
  if (!b) return null;
  const baseUrl = String(b.domain || '').replace(/\/$/, '');
  const homeCc  = String(b.homeCountryCode || 'AE').toLowerCase();
  const homeSlug = b.homeMarketSlug ? `/${b.homeMarketSlug}/` : '/';   // root brands → '/'
  const markets = [{ slug: homeSlug, locale: `en-${homeCc}`, label: 'Home (default)', xDefault: true }];

  const mkts = await getMarketsForBrandAsync(brand);
  for (const m of Object.values(mkts)) {
    const cc = String(m.countryCode || '').toLowerCase();
    if (!cc) { console.warn(`[hreflang] ${m.key || m.marketKey} has no countryCode — skipped`); continue; }
    markets.push({ slug: `/${m.marketSlug}/`, locale: `en-${cc}`, label: `${m.label} EN` });
    // Only claim an Arabic alternate when the config says that URL exists.
    if (m.arabicSlug) markets.push({ slug: `/${m.arabicSlug}/`, locale: `ar-${cc}`, label: `${m.label} AR` });
  }
  return { name: b.name || brand, baseUrl, markets };
}

const { authorize, denied } = require('./_lib/auth');
exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') return preflight();
  { const _a = await authorize(event); if (!_a.ok) return denied(); }

  const brand    = event.queryStringParameters?.brand;
  const allSlugs = await getBrandSlugs();
  const brands   = brand ? [brand].filter(b => allSlugs.includes(b)) : allSlugs;

  // GET — return markup only
  if (event.httpMethod === 'GET') {
    const result = {};
    for (const b of brands) {
      result[b] = await generateHreflangBlock(b);
    }
    return ok({ brands: result });
  }

  // POST — generate + queue approvals
  if (event.httpMethod === 'POST') {
    const body = parseBody(event) || {};
    const shouldQueue = body.queue !== false; // default true

    let queued = 0;
    const items = [];

    for (const b of brands) {
      const config = await buildHreflangConfig(b);
      if (!config) continue;
      const block  = await generateHreflangBlock(b, config);
      const marketCount = config.markets.length;

      if (shouldQueue) {
        await createApproval({
          type:  'page_update',
          brand: b,
          actor: 'hreflang generator',
          title: `Hreflang tags — ${config.name} (${marketCount} markets)`,
          reason: `International SEO: hreflang tags prevent duplicate content penalties across ${marketCount} market URLs. Add to <head> of all ${config.name} pages via your SEO plugin or theme header.`,
          payload: {
            hreflangBlock: block.html,
            hreflangJson:  block.json,
            markets:       config.markets.map(m => m.label),
            marketCount,
            wpAction:      'update_hreflang',
            implementationNote: `Paste into your WordPress theme's <head> section, or add via Yoast SEO → Search Appearance → Webmaster Tools → Custom code. This block should appear on every page of ${config.name}'s website.`,
          },
        });
        queued++;
      }

      items.push({ brand: b, markets: marketCount, queued: shouldQueue });
    }

    return ok({ queued, items });
  }

  return bad(405, 'Method not allowed');
};

async function generateHreflangBlock(brand, prebuilt) {
  const config = prebuilt || await buildHreflangConfig(brand);
  if (!config) return { html: '', json: [] };

  const { baseUrl, markets } = config;

  const tags = markets.map(m => ({
    hreflang: m.locale,
    href:     baseUrl + m.slug,
    label:    m.label,
  }));

  // Always add x-default pointing to base URL
  const xDefault = { hreflang: 'x-default', href: baseUrl + '/', label: 'x-default' };
  const allTags  = [...tags, xDefault];

  const html = [
    `<!-- Hreflang tags for ${config.name} — ${markets.length} markets -->`,
    `<!-- Generated by The Nest · ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })} -->`,
    `<!-- Add to <head> on ALL pages of ${baseUrl} -->`,
    ...allTags.map(t => `<link rel="alternate" hreflang="${t.hreflang}" href="${t.href}" /> <!-- ${t.label} -->`),
    `<!-- End hreflang -->`,
  ].join('\n');

  return { html, json: allTags };
}
