// netlify/functions/hreflang.js
// Generates hreflang markup for all international markets and queues as approval items.
//
// POST /api/hreflang { queue: true }  — generate + queue items
// GET  /api/hreflang?brand=pickl      — return markup only (no queue)
//
// Markets:
//   Pickl (6):   Bahrain, KSA, Qatar, Egypt, Jordan (/pickl-jordan/), Oman
//   Bonbird (3): Oman, Pakistan, Qatar

const { createApproval, ok, bad, preflight, parseBody } = require('./_lib/store');

const CORS = { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' };

// Hreflang config per brand
const HREFLANG_CONFIG = {
  pickl: {
    name:    'Pickl',
    baseUrl: 'https://eatpickl.com',
    markets: [
      { slug: '',              locale: 'en-ae', label: 'UAE (default)', xDefault: true },
      { slug: '/bh/',          locale: 'en-bh', label: 'Bahrain EN' },
      { slug: '/bh-arabic/',   locale: 'ar-bh', label: 'Bahrain AR' },
      { slug: '/ksa/',         locale: 'en-sa', label: 'Saudi Arabia EN' },
      { slug: '/ksa-arabic/',  locale: 'ar-sa', label: 'Saudi Arabia AR' },
      { slug: '/qatar/',       locale: 'en-qa', label: 'Qatar EN' },
      { slug: '/qatar-arabic/',locale: 'ar-qa', label: 'Qatar AR' },
      { slug: '/egypt/',       locale: 'en-eg', label: 'Egypt EN' },
      { slug: '/egypt-arabic/',locale: 'ar-eg', label: 'Egypt AR' },
      { slug: '/pickl-jordan/', locale: 'en-jo', label: 'Jordan EN' },  // NEVER change this slug
      { slug: '/oman/',        locale: 'en-om', label: 'Oman EN' },
    ],
  },
  bonbird: {
    name:    'Bonbird',
    baseUrl: 'https://bonbirdchicken.com',
    markets: [
      { slug: '',              locale: 'en-ae', label: 'UAE (default)', xDefault: true },
      { slug: '/oman/',        locale: 'en-om', label: 'Oman EN' },
      { slug: '/pakistan/',    locale: 'en-pk', label: 'Pakistan EN' },
      { slug: '/qatar/',       locale: 'en-qa', label: 'Qatar EN' },
    ],
  },
};

exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') return preflight();

  const brand  = event.queryStringParameters?.brand;
  const brands = brand ? [brand].filter(b => HREFLANG_CONFIG[b]) : Object.keys(HREFLANG_CONFIG);

  // GET — return markup only
  if (event.httpMethod === 'GET') {
    const result = {};
    for (const b of brands) {
      result[b] = generateHreflangBlock(b);
    }
    return ok({ brands: result });
  }

  // POST — generate + queue approvals
  if (event.httpMethod === 'POST') {
    const body = parseBody(event) || {};
    const shouldQueue = body.queue !== false; // default true

    let queued = 0;
    const items = [];

    for (const b of brands) {
      const config = HREFLANG_CONFIG[b];
      const block  = generateHreflangBlock(b);
      const marketCount = config.markets.length;

      if (shouldQueue) {
        await createApproval({
          type:  'page_update',
          brand: b,
          actor: 'hreflang generator',
          title: `Hreflang tags — ${config.name} (${marketCount} markets)`,
          reason: `International SEO: hreflang tags prevent duplicate content penalties across ${marketCount} market URLs. Add to <head> of all ${config.name} pages via your SEO plugin or theme header.`,
          payload: {
            hreflangBlock: block.html,
            hreflangJson:  block.json,
            markets:       config.markets.map(m => m.label),
            marketCount,
            wpAction:      'update_hreflang',
            implementationNote: `Paste into your WordPress theme's <head> section, or add via Yoast SEO → Search Appearance → Webmaster Tools → Custom code. This block should appear on every page of ${config.name}'s website.`,
          },
        });
        queued++;
      }

      items.push({ brand: b, markets: marketCount, queued: shouldQueue });
    }

    return ok({ queued, items });
  }

  return bad(405, 'Method not allowed');
};

function generateHreflangBlock(brand) {
  const config  = HREFLANG_CONFIG[brand];
  if (!config) return { html: '', json: [] };

  const { baseUrl, markets } = config;

  const tags = markets.map(m => ({
    hreflang: m.locale,
    href:     baseUrl + m.slug,
    label:    m.label,
  }));

  // Always add x-default pointing to base URL
  const xDefault = { hreflang: 'x-default', href: baseUrl + '/', label: 'x-default' };
  const allTags  = [...tags, xDefault];

  const html = [
    `<!-- Hreflang tags for ${config.name} — ${markets.length} markets -->`,
    `<!-- Generated by The Nest · ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })} -->`,
    `<!-- Add to <head> on ALL pages of ${baseUrl} -->`,
    ...allTags.map(t => `<link rel="alternate" hreflang="${t.hreflang}" href="${t.href}" /> <!-- ${t.label} -->`),
    `<!-- End hreflang -->`,
  ].join('\n');

  return { html, json: allTags };
}
